name: Update JSON Results

on:
  schedule:
    - cron: '0 18 * * 5'  # every Friday at 18:00 (6:00 PM)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Results Repository
      uses: actions/checkout@v2
      with:
        path: 'Win32APIToJson'

    - name: Clone WinmdToJson Repository
      uses: actions/checkout@v2
      with:
        repository: ricknijhuis/WinmdToJson
        path: 'WinmdToJson'

    - name: Install NuGet CLI
      run: |
        sudo apt-get install -y nuget

    - name: Install Latest win32metadata NuGet Package
      run: |
        mkdir nuget-packages
        cd nuget-packages
        nuget install Microsoft.Windows.SDK.Win32Metadata -ExcludeVersion -PreRelease

    - name: Find WinMD File
      id: find_winmd_file
      run: |
        winmd_path=$(find ./nuget-packages -name '*.winmd')
        echo "WinMD file located at: $winmd_path"
        echo "winmd_path=$winmd_path" >> $GITHUB_OUTPUT
        
    - name: Run WinmdToJson Application
      run: |
        dotnet run --project ./WinmdToJson/WinmdToJson/WinmdToJson.csproj --input ${{steps.find_winmd_file.outputs.winmd_path}} --output ./Win32APIToJson/win32

    - name: Check for Changes
      run: |
        cd Win32APIToJson
        git diff --exit-code || echo "changes_detected=true" >> $GITHUB_OUTPUT
      id: diff-check

    - name: Create Pull Request
      if: steps.diff-check.outputs.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Win32APIToJson
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b update/automated_run_${{ github.run_number }}
        git add .
        git commit -m "Update JSON results"
        git push origin update/automated_run_${{ github.run_number }}
        gh auth login --with-token <<< $GITHUB_TOKEN
        gh pr create --title "Automated JSON Update" --body "Updated JSON results from latest win32metadata and WinmdToJson application." --base main --head update/automated_run_${{ github.run_number }}
